language: minimal

jobs:
  include:
    - name: 'Retail'
      install:
        - export GAME_VERSION="retail"

    - name: 'Classic'
      install:
        - export GAME_VERSION="classic"

    - name: 'TBC'
      install:
        - export GAME_VERSION="bcc"

addons:
  apt:
    packages:
      - luarocks

before_install:
  - sudo luarocks install luacheck
  - sudo luarocks install luaunit
  - sudo luarocks install luacov

install:
  - git clone https://github.com/Beast-Masters-addons/build_utils tests/build_utils
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -d -z -g $GAME_VERSION
  - mv .release/LibProfessions/libs .

script:
  - luacheck addon --no-color -q --no-self --no-unused
  - cd tests
  - lua -lluacov test_LibProfessions.lua
  - lua -lluacov test_ProfessionApi.lua
  - lua -lluacov test_CurrentProfession.lua

after_script:
  - bash <(curl -s https://codecov.io/bash)

after_success:
  - cd $TRAVIS_BUILD_DIR
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g $GAME_VERSION
