language: minimal

jobs:
  include:
    - name: 'Live'
      install:
        - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -d -z
        - git clone https://github.com/Gethe/wow-ui-source tests/wow-ui-source
      after_success:
        - cd $TRAVIS_BUILD_DIR
        - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

    - name: 'Classic'
      install:
        - export CLASSIC_VERSION="1.13.6"
        - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -d -z -g $CLASSIC_VERSION
        - git clone https://github.com/Gethe/wow-ui-source tests/wow-ui-source -b classic
      after_success:
        - cd $TRAVIS_BUILD_DIR
        - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g $CLASSIC_VERSION

addons:
  apt:
    packages:
      - luarocks

before_install:
  - sudo luarocks install luacheck
  - sudo luarocks install luaunit
  - sudo luarocks install luacov

before_script:
  - cp -r tests .release/LibProfessions
  - cd .release/LibProfessions

  after_script:
    - python build_xml.py $TRAVIS_BUILD_DIR/.release/LibProfessions/LibProfessions.toc $TRAVIS_BUILD_DIR/.release/LibProfessions/lib.xml $TRAVIS_BUILD_DIR/lib.xml addon

script:
  - luacheck addon --no-color -q --no-self --no-unused
  - cd tests
  - lua -lluacov test_LibProfessions.lua
  - bash <(curl -s https://codecov.io/bash)